dat <-read.table('household_power_consumption.txt',sep=';',header=TRUE,na.strings = '?')
dat <-subset(dat,Date=='1/2/2007'|Date=='2/2/2007')
dt<-strptime(paste(dat$Date,dat$Time),format='%d/%m/%Y %H:%M:%S')
png(filename='plot4.png',width=480,height=480)
par(mfrow=c(2,2))
plot(dt,dat$Global_active_power, type='l',xlab='',ylab="Global Active Power")
plot(dt,dat$Voltage, type='l',xlab='datetime',ylab="Voltage")
plot(dt,dat$Sub_metering_1,type='l',xlab='',ylab='Energy Submetering',)
lines(dt,dat$Sub_metering_2,type='l',col='red')
lines(dt,dat$Sub_metering_3,type='l',col='blue')
legend('topright',c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=2, col=c('black','red','blue'))
plot(dt,dat$Global_reactive_power, type='l',xlab='datetime',ylab='Global_reactive_power')
dev.off()
